import { ArrowLeft, CheckCircle, AlertTriangle, FileText, UserCheck, TrendingUp, Brain, Info, Activity } from 'lucide-react';
import { Screen } from '../lib/types';
import { scrollToTop } from './ScrollToTop';

// Matches the API response structure
export interface DiagnosisResponse {
  diagnosed_issue: string;
  confidence_score: number;
  severity: string;
  extra_information: string;
  next_steps: string[];
  reasoning_chain: string;
}

interface DiagnosisResultsProps {
  onNavigate: (screen: Screen) => void;
  caseData: {
    caseId: string;
    // The full result object from the API
    result?: DiagnosisResponse;
  };
}

export function DiagnosisResults({ onNavigate, caseData }: DiagnosisResultsProps) {
  // Fallback if data is missing (though flow should prevent this)
  scrollToTop();
  const result = caseData.result || {
    diagnosed_issue: "Analysis Pending",
    confidence_score: 0,
    severity: "Unknown",
    extra_information: "No data available.",
    next_steps: [],
    reasoning_chain: ""
  };

  // Helper to determine severity color
  const getSeverityColor = (severity: string) => {
    const s = severity.toLowerCase();
    if (s.includes('high') || s.includes('critical')) return 'bg-red-100 text-red-700 border-red-200';
    if (s.includes('moderate') || s.includes('medium')) return 'bg-orange-100 text-orange-700 border-orange-200';
    return 'bg-green-100 text-green-700 border-green-200'; // Low or default
  };

  // Convert decimal confidence (0.8) to percentage (80)
  const confidencePercent = Math.round(result.confidence_score * 100);

  return (
    <div className="min-h-screen bg-gradient-to-br from-teal-50 via-blue-50 to-cyan-50 relative overflow-hidden">
      {/* Background Pattern */}
      <div className="absolute inset-0 opacity-10">
        <div className="absolute top-0 left-0 w-full h-full"
          style={{
            backgroundImage: 'radial-gradient(circle at 25px 25px, #29516a 2%, transparent 0%), radial-gradient(circle at 75px 75px, #29516a 2%, transparent 0%)',
            backgroundSize: '100px 100px'
          }}
        ></div>
      </div>

      {/* Glassmorphic Header */}
      <header className="relative z-10 backdrop-blur-md bg-white/30 border-b border-white/20 shadow-lg">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <button
            onClick={() => onNavigate('dashboard')}
            className="flex items-center gap-2 text-gray-700 hover:text-[#29516a] transition-colors backdrop-blur-sm bg-white/40 px-4 py-2 rounded-full"
          >
            <ArrowLeft size={20} />
            Back to Dashboard
          </button>

          <div className="flex items-center gap-3">
              <span className="text-white text-2xl">🌷</span>
            <div>
              <span className="text-2xl text-[#29516a]">Tulip</span>
              <p className="text-xs text-gray-600">Diagnosis Report</p>
            </div>
          </div>

          <div className="w-32"></div>
        </div>
      </header>

      {/* Main Content */}
      <div className="relative z-10 max-w-5xl mx-auto px-6 py-8 space-y-6">
        {/* Completion Status Card */}
        <div className="backdrop-blur-xl bg-gradient-to-br from-green-400/30 to-emerald-400/30 p-8 rounded-3xl border border-green-300/40 shadow-2xl">
          <div className="flex items-center gap-4">
            <div className="w-16 h-16 bg-white/50 backdrop-blur-sm rounded-2xl flex items-center justify-center">
              <CheckCircle className="text-green-600" size={36} />
            </div>
            <div>
              <h3 className="text-2xl text-[#29516a]">Diagnosis Complete</h3>
              <p className="text-gray-700">Case #{caseData.caseId} • {new Date().toLocaleDateString('en-US', {
                month: 'long',
                day: 'numeric',
                year: 'numeric'
              })}</p>
            </div>
          </div>
        </div>

        {/* AI Analysis Results */}
        <div className="backdrop-blur-xl bg-white/40 p-10 rounded-3xl border border-white/30 shadow-2xl space-y-8">
          <div className="flex items-start justify-between pb-6 border-b border-white/30">
            <div>
              <h2 className="text-3xl mb-2 text-[#29516a]">AI Clinical Analysis</h2>
              <p className="text-gray-600">Generated by Tulip AI Medical Engine</p>
            </div>
            <button className="flex items-center gap-2 px-6 py-3 backdrop-blur-sm bg-white/50 border-2 border-white/40 rounded-xl hover:border-[#29516a] transition-colors">
              <FileText size={18} />
              Export PDF
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Condition & Severity */}
            <div className="backdrop-blur-sm bg-gradient-to-br from-teal-400/20 to-blue-400/20 p-8 rounded-2xl border border-white/40 flex flex-col justify-center">
              <div className="flex items-center gap-3 mb-2">
                <TrendingUp className="text-[#29516a]" size={24} />
                <h3 className="text-xl text-[#29516a]">Primary Diagnosis</h3>
              </div>
              <p className="text-4xl font-bold text-[#29516a] mb-4">{result.diagnosed_issue}</p>

              <div className="flex items-center gap-3">
                <span className={`px-4 py-1 rounded-full text-sm font-medium border ${getSeverityColor(result.severity)}`}>
                  Severity: {result.severity}
                </span>
              </div>
            </div>

            {/* Confidence Score */}
            <div className="backdrop-blur-sm bg-white/50 p-8 rounded-2xl border border-white/40">
              <h3 className="text-xl mb-4 text-[#29516a] flex items-center gap-2">
                <Activity size={20} />
                AI Confidence Score
              </h3>
              <div className="flex items-end gap-2 mb-2">
                <span className="text-5xl font-bold text-[#29516a]">{confidencePercent}%</span>
                <span className="text-sm text-gray-500 mb-2">certainty</span>
              </div>

              <div className="relative w-full h-4 bg-white/60 rounded-full overflow-hidden backdrop-blur-sm border border-white/40">
                <div
                  className="absolute inset-y-0 left-0 bg-gradient-to-r from-[#29516a] via-teal-400 to-teal-500 rounded-full shadow-lg"
                  style={{ width: `${confidencePercent}%` }}
                ></div>
              </div>
              <p className="text-sm text-gray-600 mt-4">
                Based on symptom patterns and provided medical history.
              </p>
            </div>
          </div>

          {/* Extra Information */}
          <div className="backdrop-blur-sm bg-blue-50/50 p-6 rounded-2xl border border-blue-100/50">
            <h3 className="text-lg font-semibold text-[#29516a] mb-2 flex items-center gap-2">
              <Info size={20} />
              Clinical Context
            </h3>
            <p className="text-gray-700 leading-relaxed">
              {result.extra_information}
            </p>
          </div>

          {/* Reasoning Chain (New Section) */}
          {/* <div className="backdrop-blur-sm bg-white/50 p-6 rounded-2xl border border-white/40">
            <h3 className="text-lg font-semibold text-[#29516a] mb-3 flex items-center gap-2">
              <Brain size={20} />
              AI Reasoning Chain
            </h3>
            <div className="bg-white/60 p-4 rounded-xl border border-white/40 text-sm text-gray-700 font-mono whitespace-pre-wrap max-h-60 overflow-y-auto">
              {result.reasoning_chain}
            </div>
          </div> */}

          {/* Recommended Next Steps */}
          <div>
            <h3 className="text-xl mb-4 text-[#29516a] flex items-center gap-2">
              <span className="w-3 h-3 bg-[#29516a] rounded-full"></span>
              Recommended Treatment Plan
            </h3>
            <div className="space-y-3">
              {result.next_steps.map((step, idx) => (
                <div key={idx} className="flex items-start gap-4 backdrop-blur-sm bg-white/50 p-5 rounded-xl border border-white/40 hover:bg-white/60 transition-all">
                  <span className="flex-shrink-0 w-8 h-8 bg-gradient-to-br from-[#29516a] to-teal-500 text-white rounded-full flex items-center justify-center shadow-lg">
                    {idx + 1}
                  </span>
                  <p className="text-gray-800 flex-1 pt-1">{step}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Medical Disclaimer */}
          <div className="backdrop-blur-sm bg-yellow-100/60 border border-yellow-200/60 rounded-2xl p-5 flex gap-4">
            <AlertTriangle className="text-yellow-700 flex-shrink-0" size={28} />
            <div>
              <p className="text-sm text-gray-800">
                <strong className="text-yellow-800">Medical Disclaimer:</strong> This AI-generated diagnosis is for informational purposes only.
                It should not replace professional medical advice. Please consult with a healthcare provider for proper diagnosis and treatment.
              </p>
            </div>
          </div>
        </div>

        {/* Request Human Audit Section */}
        <div className="backdrop-blur-xl bg-gradient-to-br from-amber-400/30 to-orange-400/30 p-10 rounded-3xl border border-orange-300/40 shadow-2xl">
          <div className="flex items-start gap-6">
            <div className="w-20 h-20 bg-white/50 backdrop-blur-sm rounded-2xl flex items-center justify-center flex-shrink-0 shadow-lg">
              <UserCheck className="text-orange-600" size={36} />
            </div>
            <div className="flex-1">
              <h3 className="text-2xl mb-3 text-[#29516a]">Want a Second Opinion?</h3>
              <p className="text-gray-800 mb-6 leading-relaxed">
                Request verification from an external board-certified specialist. We'll securely send your case file
                and AI analysis (Case #{caseData.caseId}) to our network of human doctors for expert review. Typical response time: 24 hours.
              </p>
              <button
                onClick={() => onNavigate('audit')}
                className="px-8 py-4 bg-gradient-to-r from-[#29516a] to-teal-500 text-white rounded-xl hover:shadow-xl transition-all transform hover:scale-105"
              >
                Show Audit
              </button>
            </div>
          </div>
        </div>

        {/* Additional Actions */}
        <div className="grid grid-cols-2 gap-6">
          <div
            onClick={() => onNavigate('video')}
            className="backdrop-blur-xl bg-white/40 p-8 rounded-2xl border border-white/30 shadow-lg hover:shadow-xl transition-all cursor-pointer group"
          >
            <div className="w-16 h-16 bg-white/50 backdrop-blur-sm rounded-2xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
              <span className="text-4xl">📹</span>
            </div>
            <h3 className="text-xl mb-2 text-[#29516a]">Discuss with AI Doctor</h3>
            <p className="text-sm text-gray-600">Have questions about your diagnosis?</p>
          </div>

          <div
            onClick={() => onNavigate('dashboard')}
            className="backdrop-blur-xl bg-white/40 p-8 rounded-2xl border border-white/30 shadow-lg hover:shadow-xl transition-all cursor-pointer group"
          >
            <div className="w-16 h-16 bg-white/50 backdrop-blur-sm rounded-2xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
              <span className="text-4xl">➕</span>
            </div>
            <h3 className="text-xl mb-2 text-[#29516a]">Submit New Case</h3>
            <p className="text-sm text-gray-600">Start another diagnosis request</p>
          </div>
        </div>
      </div>
    </div>
  );
}